FilmApi\Component\Film\Domain\Model\Film:
  type: entity
  table: film
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: string
      length: 36
      unique: true
  fields:
    name:
      type: string
      length: 50
    year:
      type: string
      length: 4
    date:
      type: string
      length: 10
    url:
      type: string
      length: 255