# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    kernel.subscriber.filmMySQLListerner:
#        class: FilmApi\Component\Film\Application\EventListener\FilmListener
#        arguments:
#            entityManager: '@doctrine.orm.entity_manager'

    createFilmUseCase:
        class: \FilmApi\Component\Film\Application\Service\CreateFilm\CreateFilmUseCase
        arguments:
            eventDispatcherInterface: '@event_dispatcher'

    listFilmUseCase:
        class: FilmApi\Component\Film\Application\Service\ListFilms\ListFilmsUseCase
        arguments:
            eventDispatcherInterface: '@event_dispatcher'

    updateFilmUseCase:
        class: FilmApi\Component\Film\Application\Service\UpdateFilm\UpdateFilmUseCase
        arguments:
            eventDispatcherInterface: '@event_dispatcher'

    deleteFilmUseCase:
        class: FilmApi\Component\Film\Application\Service\DeleteFilm\DeleteFilmUseCase
        arguments:
            eventDispatcherInterface: '@event_dispatcher'